name: web3 Publish

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Push and publish ./metadata/*/unrevealed.json files to web3
        id: push-unrevealed
        uses: kubelt/web3-publish@v0-pre-alpha
        with:
          secret: ${{ secrets.NAME_PUBLISHING_KEY }}
          glob: "./metadata/*/unrevealed.json"
          published: true
          
      - run: echo '${{ steps.push-unrevealed.outputs.roots }}' >> output-unrevealed.js
      
      - name: Save output-unrevealed
        uses: actions/upload-artifact@v2
        with:
          name: output-unrevealed
          path: ./output-unrevealed.js

      - name: Push and not publish ./metadata/*/revealed.json files to web3
        id: push-revealed
        uses: kubelt/web3-publish@v0-pre-alpha
        with:
          secret: ${{ secrets.NAME_PUBLISHING_KEY }}
          glob: "./metadata/*/revealed.json"
          published: false
          
      - run: echo '${{ steps.push-revealed.outputs.roots }}' >> output-revealed.js

      - name: Save output-revealed
        uses: actions/upload-artifact@v2
        with:
          name: output-revealed
          path: ./output-revealed.js
